version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your Next.js frontend code
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your FastAPI backend code
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development  # Set your environment variables as needed
