name: Backend Preview Deployment

on:
  pull_request:
    branches:
      - "impossible-name-that-never-happens"

env:
  AWS_REGION: eu-north-1

jobs:
  deploy_backend_preview:
    name: Deploy Backend Preview
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure

      - name: Terraform Output
        run: terraform output -json > terraform-output.json
        working-directory: infrastructure
